included:
  - Sources
  - Tests

excluded:
  - .build
  - Documentation
  - .swiftlint-cache

reporter: "xcode"
cache_path: .swiftlint-cache

# Favor clarity and safety for a networking package.
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_imports
  - explicit_init
  - implicit_optional_initialization
  - redundant_nil_coalescing
  - discouraged_optional_boolean
  - multiline_parameters
  - multiline_arguments
  - multiline_arguments_brackets
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - force_unwrapping
  - force_try

analyzer_rules:
  - unused_import
  - unused_declaration

# Keep nesting shallow for readability.
nesting:
  type_level: 2

line_length:
  warning: 120
  error: 160

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

# Avoid force-unwrap/try in production code.
force_unwrapping:
  severity: error

force_try:
  severity: error
